#!/bin/sh

cd /home/maint/docker-setup/jeeves/jeeves
runuser -u maint -- git pull
cp actor/jeeves_actor.service /etc/systemd/systemd/jeeves_actor.service
systemctl restart jeeves_actor
systemctl daemon-reload